// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using newAPI2.Models;

#nullable disable

namespace newAPI2.Migrations
{
    [DbContext(typeof(context))]
    partial class contextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("newAPI2.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.ToTable("animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Description = "flies high and became bald",
                            Habitat = "mountains",
                            SpeciesName = "bald eagle"
                        },
                        new
                        {
                            AnimalId = 2,
                            Description = "walks high and became bald",
                            Habitat = "North pole",
                            SpeciesName = "bald penguin"
                        });
                });

            modelBuilder.Entity("newAPI2.Models.Bird", b =>
                {
                    b.Property<int>("BirdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BirdId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("BirdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BirdId");

                    b.HasIndex("AnimalId");

                    b.ToTable("birds");

                    b.HasData(
                        new
                        {
                            BirdId = 1,
                            Age = 22,
                            AnimalId = 2,
                            BirdName = "barad",
                            Color = "black and white"
                        },
                        new
                        {
                            BirdId = 2,
                            Age = 25,
                            AnimalId = 1,
                            BirdName = "bread",
                            Color = "blue and green"
                        });
                });

            modelBuilder.Entity("newAPI2.Models.Bird", b =>
                {
                    b.HasOne("newAPI2.Models.Animal", "Animal")
                        .WithMany("Birds")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("newAPI2.Models.Animal", b =>
                {
                    b.Navigation("Birds");
                });
#pragma warning restore 612, 618
        }
    }
}
