// <auto-generated />
using API5experiment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API5experiment.Migrations
{
    [DbContext(typeof(context))]
    [Migration("20250816120850_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API5experiment.Models.enrollment", b =>
                {
                    b.Property<int>("SId")
                        .HasColumnType("int");

                    b.Property<int>("TId")
                        .HasColumnType("int");

                    b.HasKey("SId", "TId");

                    b.HasIndex("TId");

                    b.ToTable("enrollment");

                    b.HasData(
                        new
                        {
                            SId = 1,
                            TId = 2
                        },
                        new
                        {
                            SId = 2,
                            TId = 1
                        });
                });

            modelBuilder.Entity("API5experiment.Models.student", b =>
                {
                    b.Property<int>("SId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SId");

                    b.ToTable("student");

                    b.HasData(
                        new
                        {
                            SId = 1,
                            Description = "very good reader",
                            SName = "ganes"
                        },
                        new
                        {
                            SId = 2,
                            Description = "very good dancer",
                            SName = "panis"
                        });
                });

            modelBuilder.Entity("API5experiment.Models.teacher", b =>
                {
                    b.Property<int>("TId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TId");

                    b.ToTable("teacher");

                    b.HasData(
                        new
                        {
                            TId = 1,
                            Description = " very good teacher",
                            TName = "yashanth"
                        },
                        new
                        {
                            TId = 2,
                            Description = "very bbufb",
                            TName = "baanes"
                        });
                });

            modelBuilder.Entity("API5experiment.Models.enrollment", b =>
                {
                    b.HasOne("API5experiment.Models.student", "student")
                        .WithMany("enrollments")
                        .HasForeignKey("SId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API5experiment.Models.teacher", "teacher")
                        .WithMany("enrollments")
                        .HasForeignKey("TId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("API5experiment.Models.student", b =>
                {
                    b.Navigation("enrollments");
                });

            modelBuilder.Entity("API5experiment.Models.teacher", b =>
                {
                    b.Navigation("enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
