// <auto-generated />
using API6sunday.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API6sunday.Migrations
{
    [DbContext(typeof(context))]
    [Migration("20250817180338_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API6sunday.Models.both", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int>("Did")
                        .HasColumnType("int");

                    b.HasKey("id", "Did");

                    b.HasIndex("Did");

                    b.ToTable("both");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Did = 2
                        },
                        new
                        {
                            id = 2,
                            Did = 1
                        });
                });

            modelBuilder.Entity("API6sunday.Models.department", b =>
                {
                    b.Property<int>("DId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DId");

                    b.ToTable("depts");

                    b.HasData(
                        new
                        {
                            DId = 1,
                            Description = "very good place",
                            Dname = "hyderabad"
                        },
                        new
                        {
                            DId = 2,
                            Description = "very nice plklac e",
                            Dname = "bangalore"
                        });
                });

            modelBuilder.Entity("API6sunday.Models.employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("emps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "adnijkadn",
                            Name = "yahswuaj"
                        },
                        new
                        {
                            Id = 2,
                            Description = "bhasjdad",
                            Name = "baubhjd"
                        });
                });

            modelBuilder.Entity("API6sunday.Models.both", b =>
                {
                    b.HasOne("API6sunday.Models.department", "department")
                        .WithMany("both")
                        .HasForeignKey("Did")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API6sunday.Models.employee", "employee")
                        .WithMany("both")
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("API6sunday.Models.department", b =>
                {
                    b.Navigation("both");
                });

            modelBuilder.Entity("API6sunday.Models.employee", b =>
                {
                    b.Navigation("both");
                });
#pragma warning restore 612, 618
        }
    }
}
