// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using relmanytomany.Models;

#nullable disable

namespace relmanytomany.Migrations
{
    [DbContext(typeof(context))]
    [Migration("20250816103643_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("relmanytomany.Models.both", b =>
                {
                    b.Property<int>("bid")
                        .HasColumnType("int");

                    b.Property<int>("cId")
                        .HasColumnType("int");

                    b.HasKey("bid", "cId");

                    b.HasIndex("cId");

                    b.ToTable("both");

                    b.HasData(
                        new
                        {
                            bid = 1,
                            cId = 2
                        },
                        new
                        {
                            bid = 2,
                            cId = 1
                        });
                });

            modelBuilder.Entity("relmanytomany.Models.cantfly", b =>
                {
                    b.Property<int>("cId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cId"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("bname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cId");

                    b.ToTable("cantflybirds");

                    b.HasData(
                        new
                        {
                            cId = 1,
                            age = 22,
                            bname = "b SJK"
                        },
                        new
                        {
                            cId = 2,
                            age = 34,
                            bname = "yashoo"
                        });
                });

            modelBuilder.Entity("relmanytomany.Models.fly", b =>
                {
                    b.Property<int>("bId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bId"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("cname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bId");

                    b.ToTable("birds");

                    b.HasData(
                        new
                        {
                            bId = 1,
                            age = 4,
                            cname = "yashwanth"
                        },
                        new
                        {
                            bId = 2,
                            age = 8,
                            cname = "jnadk"
                        });
                });

            modelBuilder.Entity("relmanytomany.Models.both", b =>
                {
                    b.HasOne("relmanytomany.Models.fly", "fly")
                        .WithMany("both")
                        .HasForeignKey("bid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("relmanytomany.Models.cantfly", "cantfly")
                        .WithMany("both")
                        .HasForeignKey("cId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cantfly");

                    b.Navigation("fly");
                });

            modelBuilder.Entity("relmanytomany.Models.cantfly", b =>
                {
                    b.Navigation("both");
                });

            modelBuilder.Entity("relmanytomany.Models.fly", b =>
                {
                    b.Navigation("both");
                });
#pragma warning restore 612, 618
        }
    }
}
